# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: scripts/format.sh
        language: system
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: scripts/lint.sh
        require_serial: true
        language: python
        types: [ python ]
