"""init

Revision ID: dc818d614a02
Revises: 
Create Date: 2025-04-19 10:54:13.291951+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc818d614a02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_body_gin', 'incidents', ['body'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_incidents_hash'), 'incidents', ['hash'], unique=False)
    op.create_index('ix_incidents_headers_gin', 'incidents', ['headers'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incidents_headers_gin', table_name='incidents', postgresql_using='gin')
    op.drop_index(op.f('ix_incidents_hash'), table_name='incidents')
    op.drop_index('ix_incidents_body_gin', table_name='incidents', postgresql_using='gin')
    op.drop_table('incidents')
    # ### end Alembic commands ###
